Repository DFE-Digital/access-your-teaching-qualifications, pull requests merged in 2024-09, with the labels that each got.

#818 Remove CBL data from CTR
  .github/workflows/build-and-deploy.yml
  Gemfile
  Gemfile.lock
  app/components/check_records/teacher_profile_summary_component.rb
  app/lib/qualifications_api/teacher.rb
  app/models/sanction.rb
  spec/components/check_records/teacher_profile_summary_component_spec.rb
  spec/models/sanction_spec.rb
  spec/system/check_records/user_searches_for_teacher_with_restrictions_spec.rb
Labels: deploy-aks

#848 [2049] Upgrade postgres to version 16
  terraform/application/database.tf
Labels: devops, deploy-aks

#846 Add redirect to sign out complete page
  app/controllers/qualifications/users/sign_out_controller.rb
  spec/system/qualifications/user_signs_out_spec.rb
  spec/system/qualifications/user_signs_out_via_onelogin_spec.rb
Labels: deploy-aks

#853 [2048] Remove app service IP restriction
  terraform/app.tf
Labels: devops
